
version: 2

sources:
  - name: erp
    description: Fonte do ponto de vendas da NorthWind
    schema: erp_northwind
    tables:

      - name: employees
        description: Tabela com informações de Funcionários.
        columns:
          - name: employee_id
            description: Chave primária da tabela Funcionários.
            tests:
              - unique
              - not_null