
version: 2

sources:
  - name: erp
    description: Fonte do ponto de vendas da NorthWind
    schema: erp_northwind
    tables:

      - name: employees
        description: Tabela com informações de Funcionários.
        columns:
          - name: employee_id
            description: Chave primária da tabela Funcionários.
            tests:
              - unique
              - not_null

      - name: order_details
        description: Tabela com informações dos pedidos.
        columns:
          - name: order_id
            description: Chave primária da tabela order.
            tests:
              - not_null
          - name: product_id
            description: Chave primária da tabela product.
            tests:
              - not_null

      - name: orders
        description: Tabela com informações dos pedidos.
        columns:
          - name: order_id
            description: Chave primária da tabela order.
            tests:
              - not_null
              - unique
      
      - name: categories
        description: Tabela com informações de categoria de produtos.
        columns:
          - name: category_id
            description: Chave primária da tabela de Categorias.
            tests:
              - unique
              - not_null

      - name: customers
        description: Tabela com informações do consumidor.
        columns:
          - name: customer_id
            description: Chave primária da tabela customer.
            tests:
              - unique
              - not_null

      - name: suppliers
        description: Tabela com informações dos fornecedores.
        columns:
          - name: supplier_id
            description: Chave primária da tabela suppliers.
            tests:
              - not_null
              - unique

      - name: products
        description: Tabela com informações dos produtos.
        columns:
          - name: product_id
            description: Chave primária da tabela product.
            tests:
              - not_null
              - unique